spring:
  application:
    name: spring-boot-essential-reuniones
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api/rest

logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: DEBUG
        jdbc:
            datasource:
                init:
                  ScriptUtils: DEBUG
